### ISSUE TITLE
Populate mercurial entries based on input number for spells

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#209]
if the user inputs a mercurial magic number in a spell entry, populate the mercurial text automatically

**Comment by mooped** [comment]
Override the confirmation dialog to prompt for a) roll b) lookup c) clear.

**Comment by mooped** [comment]
Add title attribute when disabled to indicate that it can be rolled once on a character sheet.

**Comment by mooped** [comment]
![mercurial_lookup](https://user-images.githubusercontent.com/371357/125174582-4bff7200-e1be-11eb-96c9-95bfd2afc824.gif)

You can now lookup mercurial effects (on dev).

The title attribute comment is moot since the button is no longer visible when the sheet is not owned. I also can't think of a great reason to allow clearing the result, possibly this is something that should happen automatically when dragged to the item directory though.
