### ISSUE TITLE
Feature/Functionality Requests: Legacy Judge QOL - Mercurial Item Entry and CS PDF Exporter

### ISSUE THREAD

**Issue by justinthejaguar** [foundryvtt-dcc/dcc#235]
Feature/Function Request 1: Allow Mercurial Effects to be entered as items from a compendium.
Benefit: This will benefit Legacy Judge's in preparation of games for players coming from other systems of play, and cut down prep time for the Wizard and Elf classes.

Feature/Function Request 2: Allow the Judge or Player to export a character onto the Form Fillable PDF offered through Legacy rulings so that it can be distributed immediately after players have updated the sheet for the next Legacy game.

Feature/Function Request 3: Is it possible to add designated fields in character sheets to indicate currency, which can potentially be used in reference to the item prices in the compendium. My thought here is the eventuality of having more in relation to loot sheets, shops, etc.

**Comment by mooped** [comment]
I'm closing this but I've created individual issues for each item. I've also added some comments below.

> Feature/Function Request 1: Allow Mercurial Effects to be entered as items from a compendium.
> Benefit: This will benefit Legacy Judge's in preparation of games for players coming from other systems of play, and cut down prep time for the Wizard and Elf classes.

I'll have a think about the best way to do this. Currently we support assigning from the number but I know you mentioned this doesn't always help if people don't keep their legacy sheets well. Maybe it can just be a dropdown on the spell sheet if the Core Book is loaded, but I need to think about how it would fit in the UI.

> Feature/Function Request 2: Allow the Judge or Player to export a character onto the Form Fillable PDF offered through Legacy rulings so that it can be distributed immediately after players have updated the sheet for the next Legacy game.

I had a play with this before ReaverCon and I discovered that it was easy to get into a PDFoundry sheet, but this doesn't help as there's no way to export a PDF from it. They were originally considering this as a feature, but appear to have abandoned that due to security concerns. There are other services that generate PDFs online, but none that I found that work with form fillable sheets so I didn't get very far. There's also the issue of how we distribute the PDFs to think about.

I've seen talk on the Foundry Discord that someone was working on a PDF Exporter module. If that gets off the ground we can integrate with it.

> Feature/Function Request 3: Is it possible to add designated fields in character sheets to indicate currency, which can potentially be used in reference to the item prices in the compendium. My thought here is the eventuality of having more in relation to loot sheets, shops, etc.

I like this idea and I'm not too happy with the current solution of merging 'As Coin's items into one of those items.
