### ISSUE TITLE
with Roll Attack Bonus checked, if you have a die in the attack bonus box, clicking into the box rolls dice

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#236]
Steps to reproduce: 
Enable Roll Attack Bonus
Put a die in the Attack Bonus field
Click into Attack Bonus

**Comment by mooped** [comment]
I thought we'd fixed this, but it seems to have regressed.

Only the field label should be have a click handler registered.

**Comment by mooped** [comment]
This was caused by a rework of how the rollable elements were registered, which was catching the whole attack-bonus container as well as the label, but it was hidden by another bug I fixed recently.

I've committed a fix for the next release (which will probably be the final release for FVTT 0.7.9).
