### ISSUE TITLE
Document that all rollable items on the sheet can be dragged to the Hot Bar to create a macro

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#237]
If you click and hold, you can drag Intelligence, it doesn't do anything, but it looks janky.

![image](https://user-images.githubusercontent.com/7275595/118581183-31c98a80-b75f-11eb-9a7d-22a677bff9f4.png)

**Comment by mooped** [comment]
This is intentional. All fields can be dragged. If you drop them on the Hotbar it creates a macro for the relevant roll.

We should perhaps make this clearer to the user by adding it to the user guide.

Some fields have slightly special behaviour. If you drag Luck you get a roll under luck check, if you drag the Luck modifier you get a non-standard roll over luck check since some modules call for them. If you drag the Action Dice field you get a macro that sets the action die to the one selected when the field was dragged.

**Comment by algnc** [comment]
Fixed in https://github.com/foundryvtt-dcc/dcc/wiki/Dragging-rollable-items-to-the-macro-bar
