### ISSUE TITLE
Swap colors for Deed Die macro and Lay on Hands

### ISSUE THREAD

**Issue by algnc** [foundryvtt-dcc/dcc#59]
If I drag the Deed roll, or Lay On Hands, to the macro bar, they are black. If the screen has a black background or lots of fog of war, they are really tough to see. If the icon were white, like the other equipment icons, it should work OK for a new player.

**Comment by mooped** [comment]
Might be good to make them white with a black border so there's contrast against any background.

Here's the full list of macro icons we use, it would be good to get 'correct' icons for most or high contrast versions of the existing ones:
- Ability roll (d20?)
- Initiative
- Saves
  - Ref
  - Fort
  - Will
- Skill rolls (usually thief skills, but also used for some other situations)
- Luck die (d3 could work since that's the level 1 luck die, currently it's a d4)
- Spell Check - currently a starburst from core Foundry
- Deed roll (currently also a d4, could also be a d3 I guess)
- Weapon Attacks - These already work okay with the sheet icons, but might be good to add a black border
  - Ranged
  - Melee

**Comment by mooped** [comment]
A set of icons for each of the dice chain would be good for action die macros.

**Comment by cyface** [comment]
Can we / should we add initiative to the hot bar, given how it does/doesn't work with the encounter tool?

**Comment by mooped** [comment]
Looking at how it works, Font Awesome as Foundry uses it is literally a font, so we can't use it where Foundry is expecting an image.

It uses the css content property to put an appropriate unicode character into the element that's representing the icon.

They do also provide SVG downloads of the icons so we could use their (free) icons under the CC BY 4.0 license (https://fontawesome.com/license/free).

**Comment by cyface** [comment]
I think using the CC BY licensed FA icons and the game-icon.net icons is the way to go!
